# Generated by Django 5.1 on 2024-08-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('link_github', models.URLField(blank=True, null=True)),
                ('link_online', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
    ]
