# Generated by Django 5.1 on 2024-08-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_proyecto',
            field=models.ImageField(blank=True, null=True, upload_to='imgprojects/', verbose_name='Imagen de proyecto'),
        ),
    ]
