# Generated by Django 5.1 on 2024-08-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyecto_imagen_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
